### ISSUE TITLE
Errors don't implement `std::error::Error`

### ISSUE THREAD

**Issue by thomaseizinger** [teawithsand/torut#12]
Issue as per title. Is this intentional? Would you accept a PR that implements `std::error::Error` for the `Error` types in this crate?

**Comment by teawithsand** [comment]
Mainly, I've used big enum for error handling because back at a time when I started writing this library downcasting was only in nightly rust(or at least I thought so), so enums were the only sensible option for getting cause of error. That being said, after doing some research I think that it's good idea to implement std error type(without breaking backwards compatibility). I'll probably implement myself it or accept PR.

**Comment by thomaseizinger** [comment]
Cool, thanks for the clarification!

Implementing std::Error will make interop with libraries like `anyhow` possible which became somewhat of a defacto standard lately.

I'll stand by then, let me know if you want a PR instead.

**Comment by teawithsand** [comment]
I've implemented `std::error::Error` trait for `ConnError` and onion service errors. This should work. That being said I didn't change structure of errors. They are still enums, so old code should work.

**Comment by thomaseizinger** [comment]
> I've implemented `std::error::Error` trait for `ConnError` and onion service errors. This should work. That being said I didn't change structure of errors. They are still enums, so old code should work.

Amazing, thank you.

Regarding enums, it is my understanding that this is state-of-the-art error handling in Rust for libraries so need to change that :)
