### ISSUE TITLE
Improve how to keep a hidden service, created by the control port, up 

### ISSUE THREAD

**Issue by tee8z** [teawithsand/torut#17]
In the make_onion_v3.rs example file, it looks like the only way to keep the hidden service up, after creating it with the control port, is by doing something like the following: 
``` 
println!("Added onion service v3!");
loop {
    sleep(Duration::from_secs(1)).await;
    if shutdown_signal_tor.is_triggered() {
            break;
     }
}

println!("Deleting created onion service...");
```
Is there a better way to keep the hidden service running, beside sleeping in a loop until a shutdown signal is sent? I would assume internally the library would keep the stream open, even after leaving the function where it was opened, until the following is called from somewhere else: 
```
 // delete onion service so it works no more
 ac.del_onion(&key.public().get_onion_address().get_address_without_dot_onion()).await.unwrap();
```
A piece that would really help with this also would be making the struct AuthenticatedConn able to be cloned, allowing it to be more easily passed out of the original function it was created in.

**Comment by teawithsand** [comment]
> I would assume internally the library would keep the stream open, even after leaving the function where it was opened, until the following is called from somewhere else:

I guess it's not about tor's control protocol connection, but about onion service. In general handling streams, which are created by someone connecting to hidden service and then local tor instance connecting to some address/port is out of scope of this library.

EDIT: `add_onion_v3` and in the past `add_onion_v2` return `()` or error, not some smart guard, so liveness of onion service is managed by tor/it's controller, so yes, it outlives current scope in that sense.

The first thing, which comes to my mind is to simply set the detach flag and then kill(DEL_ONION) onion service from separate control protocol connection, since by default onion services are attached to current control protocol connection and automatically removed once control connection is closed.

> Is there a better way to keep the hidden service running, beside sleeping in a loop until a shutdown signal is sent?
If detach flag is set, you can exit connection and exit process. Otherwise the answer is probably no.

Aside from that, you have to keep the tor control protocol connection open if you do not want to set the detach flag. There is no better way for keeping onion service alive. Tor CP connection is alive as long as Conn object is not dropped(in most cases it's wrapped by some other object, like authenticated conn).

> A piece that would really help with this also would be making the struct AuthenticatedConn able to be cloned, allowing it to be more easily passed out of the original function it was created in.

It would require implementing some synchronization mechanism under the hood. Now it simply wraps the TCP connection and performs reads/writes(with async/await ofc). I think that the simplest way to achieve such behavior is to use `Arc<Mutex<X>>` with some async aware mutex(sth like https://docs.rs/async-mutex/latest/async_mutex/), if needed.

Aside from that, due to it's nature, you probably should borrow/move it. Think of it as smart TCP stream.

Otherwise accessing single connection from many threads does not make much sense.

I am not sure if I've answered your question so feel free to correct me and/or respond.

PS. I haven't tried the detach flag lately, but I remember that there was some.

https://github.com/torproject/torspec/blob/main/control-spec.txt

Here's link to tor CP spec, which says:
In `ADD_ONION` section:
>  "Detach"    / ; Do not associate the newly created Onion Service
>                        to the current control connection.

whatever that means.
